### ISSUE TITLE
.otx paketi

### ISSUE THREAD

**Issue by emelsimsek** [tdd-ai/hunspell-tr#1]
Merhaba,

   Extension olarak kurulabilmesi için gereken .otx dosyasını yayınlar mısınız? 

Teşekkürler.

**Comment by alisafaya** [comment]
Merhaba @emelsimsek, 

Dictionary icin ornek otx package paylasabilir misiniz?

**Comment by emelsimsek** [comment]
https://wiki.documentfoundation.org/Development/Create_a_Hello_World_LibreOffice_extension sayfasında bir extension paketinin nasıl oluşturulduğu anlatılıyor. 
Bu sayfaya gözattıktan sonra, aşağıdaki linkte bulunan sözlük extension paketini örnek alabilirsiniz:
https://netix.dl.sourceforge.net/project/aoo-extensions/18079/0/oo-turkish-dict-v1.3.oxt
Aslında bir zip dosyası olan otx paketini unzip ederek inceleyebilirsiniz.

otx paketi oluşturulduktan sonra, https://extensions.openoffice.org adresinde https://extensions.openoffice.org/en/project/turkish-spellcheck-dictionary örneğindeki gibi yayınlamaya çalışabiliriz.

**Comment by alisafaya** [comment]
Merhaba, 

Ilgili paketi olusturduk, release'a ekledik: https://github.com/tdd-ai/hunspell-tr/releases/tag/v1.1.0
