### ISSUE TITLE
Bir kod yayinlacak misiniz?

### ISSUE THREAD

**Issue by asfix** [tdd-ai/hunspell-tr#2]
Merhaba.

Bu bir kutuphane ise python tabanli bir versiyonu var mi? Varsa alip yazim hatalarini duzeltmek istemekteyim. Yardimci olabilir misiniz?

**Comment by alisafaya** [comment]
Merhaba, 

Hayir bu bir kutuphane degil, bir sozluktur. Onu kullanmak icin https://pypi.org/project/cyhunspell/ package'ini kullanabilirsin. 

aff ve dic uzantili dosyalari repomuzdan indirdikten sonra:

```python
from hunspell import Hunspell

h = Hunspell('tr_TR', hunspell_data_dir='/custom/dicts/dir')

h.spell('merhaba')
h.spell('mrhaba')
h.suggest('mrhaba')
```

seklinde kullanabilirsin.
